server:
  port: 8585
  servlet:
    context-path: /api
spring:
  application:
    name: ai-agent
  profiles:
    active: default
  ai:
    dashscope:
      api-key: xxx
      chat:
        options:
          model: qwen-plus
          stream: true
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: ollama3

# searchApi
search-api:
  api-key: xxx

# springdoc-openapi ????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.belly.aiagent.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn